### ISSUE TITLE
Stopping VPinballX.starter should also stop the VPinball subprocess

### ISSUE THREAD

**Issue by JockeJarre** [JockeJarre/VPinballX.starter#11]
PinballY starts the table - the capture "countdown-window" is visible, counts from 20 to 0, then the both captures for backglass and playfield are ok. BUT after this the "table"-task (a.k.a. the vpinballx.exe) won't close.
it needs to manually press ESC to close and return to PinballY

**Comment by Karl030167** [comment]
i think i'm the fastest beta tester ;-)
YES, now it works as intended. 
PinballY opens the table: 
(in background it starts your "renamed" starter.exe - this starts the real vpinballx.exe as set in starter.ini,  countdown window appears, capuring is ok, "real vpinballx.exe" closes, back to PinballY 
you are a wizard, no doubt. Just look at the size of this thing...
before the starter.exe was ~13.000 kb,  now its only ~570 kb. And works as it should !
i think this issue can be closed.  Thank you again for your efforts

**Comment by JockeJarre** [comment]
If you would be so kind and comment on VPU... will release first though...
