### ISSUE TITLE
Add possibility to add pre and post command

### ISSUE THREAD

**Issue by JockeJarre** [JockeJarre/VPinballX.starter#13]
Add possibility to add pre and post cmd file which runs before and after a table is started.

If there is a table "Blood Machines (VPW 2022).vpx" and it is started through VPinballX.starter, it will then search for a file "Blood Machines (VPW 2022).pre.cmd" and "Blood Machines (VPW 2022).post.cmd" if it is activated in the configuration.

If active it will call these cmd batch files before and after starting the VPX executable. In these scripts, it is possible to add different tweaks, starting processes, copying files or whatever you can imagine...

**Comment by JockeJarre** [comment]
Add support to have different configuration depending on calling program

**Comment by Karl030167** [comment]
Your tool is unbelievable!
It's even possible to use the .pre and .post files to change Vpinmame.dll versions.
I did this for World Poker Tour, because this table (and maybe some others) needs older Vpinmame for working table light inserts.
It works great! The possibilities are endless...

**Comment by JockeJarre** [comment]
> Your tool is unbelievable! It's even possible to use the .pre and .post files to change Vpinmame.dll versions. I did this for World Poker Tour, because this table (and maybe some others) needs older Vpinmame for working table light inserts. It works great! The possibilities are endless...

Thanks, happy you like it! Would you be so kind and write a review on VPU? And maybe include your pre/post files as example.

**Comment by JockeJarre** [comment]
It is now possible to have different pre/post commands depending on where the starter was called from:

``` ini
;you can have different settings depending on the caller: (Pinup popper show up as anonymous)
PREPOSTactive.explorer=true
PREcmdExtension.explorer=.explorerpre.cmd
POSTcmdExtension.explorer=.explorerpost.cmd
```
