### ISSUE TITLE
No .exe file

### ISSUE THREAD

**Issue by thescrapyarduk** [JockeJarre/VPinballX.starter#2]
Downloaded package zip but no main .exe and cannot find main .exe in package file list. Doesn't appear to be any .exe files in package to run the loader

Thanks

**Comment by JockeJarre** [comment]
Thanks for checking, though I do not understand where you try to download.

Please check under releases:
https://github.com/JockeJarre/VPinballX.starter/releases
Then under Assets, you will find [VPinballX.starter-1.0.42-44df490-Release-win-x64.zip](https://github.com/JockeJarre/VPinballX.starter/releases/download/v1.0-44df490/VPinballX.starter-1.0.42-44df490-Release-win-x64.zip). 

Once unzipped (using 7-zip or similar unzip tool which can unblock the files) you have one exe which when double-clicked will generate the ini file for you (this is only a template and you need to modify it before usage)

I just tried it out without any problems.

**Comment by thescrapyarduk** [comment]
Found straight away after you pointed out its under "releases". I looked under "go to file" as no releases listed obviously, unless you actually click on "releases" or the tags then its all there

Thanks

**Comment by JockeJarre** [comment]
Thanks for the thumbs up.  I will update the readme in the main page to make it more obvious.

If you like the tool, please star it on the top. :)
