### ISSUE TITLE
32 and 64 bit handling possible?

### ISSUE THREAD

**Issue by 5cutters** [JockeJarre/VPinballX.starter#3]
Love the idea behind the starter app!

Would it be possible to include 32 and 64 bit handling to the launched executable.

I appreciate this may not be possible without changes to how VPX writes table files to include extra data (but i don't know) so might only work for 10.8+ tables if a change is needed there.

This would be useful for the handful of tables that don't play well in 64 bit at the moment (some Stern roms etc)

**Comment by JockeJarre** [comment]
I have been thinking of something like:

``` ini
;A Configuration file for VPinballX.starter
[VPinballX.starter]
;DefaultVersion when started without any table param.
DefaultVersion=10.80
LogVersions=1
[Tables]
Blood Machines*=10.80x64
[VPinballX]
;Default value to be used if not found in the table below.
Default=VPinballX72.exe
;File versions converted to the right VPinballXxx.exe
10.60=VPinballX62.exe
10.70=VPinballX71.exe
10.72=VPinballX72.exe
10.80=VPinballX85.exe
10.80x64=VPinballX85x64.exe
```
It would do specific table to specific version. But I haven't finalized the idea yet...

What are your thoughts about it?

**Comment by 5cutters** [comment]
The only downside i can see with your proposal using per table exceptions is that i think people will just forget they set it. 

E.g. If TableA has an exception set to use 10.7x32 but the table is then updated to 10.8 they'd have to remember to update the ini file. My suspicion is they'd forget, at least until they tried to play the table anyway ;)

**Comment by JockeJarre** [comment]
Or should we base a automated selection x86 / x64 on the size of the table file? I would not know any other way to "automate" it.

Or one could name the table file "Blood Machines (VPW 2022) x64.vpx" to have it use x64 counterpart?

**Comment by 5cutters** [comment]
Out of those two the table file name works best for me.

How about a variation of your original idea. But assume most tables will work in 64 bit (and going forward will probably need it), so the per table exception list is for 32bit only tables (i got the list from [https://vpuniverse.com/forums/topic/9203-64-bit-table-list](url) ) 

E.g.
``` ini
;A Configuration file for VPinballX.starter
[VPinballX.starter]
;DefaultVersion when started without any table param.
DefaultVersion=10.80
LogVersions=1
[32bit Tables]
;Specify table exceptions to use x86 (32 bit) version
;examples - The Walking Dead, Cactus Canyon Continued, Baby Pacman, Granny and the Gators, Caveman, Star Wars LE
Blood Machines*
[VPinballX]
;Default value to be used if not found in the table below.
Default=VPinballX72.exe
;File versions converted to the right VPinballXxx.exe
10.60=VPinballX62.exe
10.70=VPinballX71.exe
10.72=VPinballX72.exe
10.72x86=VPinballX72x86.exe
10.72=VPinballX72.exe
10.80x86=VPinballX85x86.exe
10.80=VPinballX85.exe
```
or that might be better as?

``` ini
10.72x86=VPinballX72.exe
10.72=VPinballX72x64.exe
10.80x86=VPinballX85exe
10.80=VPinballX85x64.exe
```

I assume the * could work as a wildcard in the per table exceptions. People would need to be careful when adding Star Wars as an exception as there's a lot of Star Wars themed tables.

**Comment by JockeJarre** [comment]
yes, the "*" is a simple wildcard, would not add full regex here but simple wildcards. Will check if I get some time soon to investigate what can be made here

**Comment by JockeJarre** [comment]
What about:

``` ini
;A Configuration file for VPinballX.starter
[VPinballX.starter]
;DefaultVersion when started without any table param.
DefaultVersion=10.80
LogVersions=1
[TablesNameExceptions]
x32=x32
x64=x64
[VPinballX]
;Default value to be used if not found in the table below.
Default=VPinballX72.exe
;File versions converted to the right VPinballXxx.exe
10.60=VPinballX62.exe
10.70=VPinballX71.exe
10.72=VPinballX72.exe
10.80=VPinballX85.exe
10.80x64=VPinballX85x64.exe
10.80x32=VPinballX85x32.exe
```

which means, if you start "Blood Machines (VPW 2022) x32.vpx" it will find "x32" in the name and will build "10.80x32" out of the version number and the value to the right and will use "VPinballX85x32.exe".

**Comment by 5cutters** [comment]
The only downside i can see to that is people will have to rename some of their table files. Not sure if that will mean needing to rename table media to match in some front ends or not (who knows all the front ends?). 

I don't think there's an 'ideal' way of dealing with exceptions though tbh, unless VPX starts stamping table files with the platform information as well as the version in the save information. So i guess it might just be best to do what's easiest for you, if it works then i'll be happy anyway!, it is after all only to deal with a handful of exceptions so no point over engineering it ;)

**Comment by JockeJarre** [comment]
As long as you can configure it once, and then forget about it. It should work in the background and do it's job well

**Comment by 5cutters** [comment]
Agree, set and forget is ideal.

Just on your last suggestion, if the x64 exception is removed would this still work?

;A Configuration file for VPinballX.starter
[VPinballX.starter]
;DefaultVersion when started without any table param.
DefaultVersion=10.80
LogVersions=1
[TablesNameExceptions]
;add suffix to table file name
x32=x32
[VPinballX]
;Default value to be used if not found in the table below.
Default=VPinballX72.exe
;File versions converted to the right VPinballXxx.exe
10.60=VPinballX62.exe
10.70=VPinballX71.exe
10.72=VPinballX72.exe
10.80=VPinballX85.exe
10.80x32=VPinballX85x32.exe

Note - i'm not suggesting you change the default ini file,  just checking if the app would still work as designed in the way i'd probably want to use it (only one copy of the 10.8 x64 exe and that would be default)

**Comment by JockeJarre** [comment]
Yes, of course. You could even do like this:

``` ini
;A Configuration file for VPinballX.starter
[VPinballX.starter]
;DefaultVersion when started without any table param.
DefaultVersion=10.80
LogVersions=1
[TablesNameExceptions]
; If this string is found in the Table filename, we will use the string to the right to add to the version number search
x32=x32
Table Name=x32
Another Table=GL
[VPinballX]
;Default value to be used if not found in the table below.
Default=VPinballX74.exe
;File versions converted to the right VPinballXxx.exe
10.80=VPinballX85.exe
10.80x32=VPinballX85x32.exe
10.80GL=VPinballX85_GL.exe
```
So you could either add a x32 to those tables where you want to x32 exe OR you specify part of the table name in the ini and it should also use that same executable. But the link between the two has to be somewhere...
but as you see, there is no hard logic in the TablesNameExceptions (or whatever it should be called) it is just strings searched for in the incoming FileName and looked up using Version+the string in the [VPinballX] table.

**Comment by 5cutters** [comment]
Awesome... really like how flexible that would be!
(not sure if you'd still allow wildcards or not, if they are then i suppose the x32=x32 should be *x32=x32 ?  , small detail anyway, everything else makes sense and sounds great)

**Comment by JockeJarre** [comment]
No, I would skip wildcards in this case, as long as the string is found in the table name we are good to go

**Comment by JockeJarre** [comment]
Works as discussed, closing
