### ISSUE TITLE
Drag drop table file feature request

### ISSUE THREAD

**Issue by 5cutters** [JockeJarre/VPinballX.starter#4]
Would it be possible to add a drag drop feature for table files onto VPinballX.starter.exe so that when editing a table the correct editor is opened)?

This would be for editing tables / initial setup when changing script options etc.

**Comment by JockeJarre** [comment]
It does that already?!?? try right clicking a vpx file and select edit. 
It will trigger **VPinball.starter** (that is, if you have replaced your **VPinballX.exe** with **VPinball.starter**)

**Comment by 5cutters** [comment]
Ahh.. thanks.
I haven't tried it on the cab yet but was testing on my desktop.. and on my desktop i'd associated .vpx files with 7zip a while ago as it's a lot quicker to open the file in 7zip just to check the script options etc rather than opening the file in the vpx editor.

I'm sure it'll work fine on the cab then where i haven't changed file associations. It's probably only me that views vpx file in 7zip anyway :)
