### ISSUE TITLE
Possible Enhancement - Add VPX process priority options

### ISSUE THREAD

**Issue by 5cutters** [JockeJarre/VPinballX.starter#6]
Just a thought, but maybe lower end systems could benefit from an ini option to set the vpx launch priority via Process.PriorityClass

Default to Normal, but allow AboveNormal and maybe High (?) as options.

On my old setup running at above normal priority did seem to help with in game performance (but it may have been a placebo effect). Can't really check now as i've now got better hardware.

Like i say, just an idea. Not sure if it's something you'd want to add or not

**Comment by JockeJarre** [comment]
Never thought that this would be needed?

**Comment by 5cutters** [comment]
Needed?.. probably not, just a bit of extended functionality that might help some users.

Could be just plain old feature creep though, so i understand if you see it that way and and close this off with no action!

**Comment by JockeJarre** [comment]
If more requests comes we can always open it again
