### ISSUE TITLE
choose vpx independent of table version

### ISSUE THREAD

**Issue by Karl030167** [JockeJarre/VPinballX.starter#7]
example:
most tables with "version 10.72" are working very good with vpx8 (and want to use it because of extended pov settings...)
only very few tables with "version 10.72" need vpx version <= 10.74

how could i set an ini (TableNameExceptions ?) so all .vpx tables (10.72,10.73, 10.80,...) start with default vpx10.8,
but only the few "problematics" start with vpx10.74 ?

**Comment by JockeJarre** [comment]
I would try like this

1. Set both defaults to 10.80
2. If "Table Name" is found in the table name we want to find Default.RevertX7 independent on the version of VPX used for saving. (Unless explicitly saved for 10.80) OR if X7 is added to the table name, the same effect.

``` ini
;A Configuration file for VPinballX.starter
[VPinballX.starter]
;DefaultVersion when started without any table param.
DefaultVersion=10.80
LogVersions=1
[TableNameExceptions]
;If left string is found in the Table filename; ;we will use the right string to add to the version number search
Table Name=.RevertX7
x32=x32
GL=GL
X7=.RevertX7
[VPinballX]
;Default value to be used if not found in the table below.
Default=VPinballX85.exe
Default.RevertX7=VPinballX74.exe
;File versions converted to the right VPinballXxx.exe
10.80=VPinballX85.exe
10.80x32=VPinballX85x32.exe
10.80GL=VPinballX85_GL.exe
```

It could work, but has to be tested. And if it doesn't work we could consider adding support for it?
What do you think, how could this be modeled in the ini file?

**Comment by Karl030167** [comment]
tried your suggestion, but no effect
my ini:

> ;A Configuration file for VPinballX.starter
[VPinballX.starter]
;DefaultVersion when started without any table param.
DefaultVersion=10.80
LogVersions=1
[TableNameExceptions]
;If left string is found in the Table filename
;we will use the right string to add to the version number search
;Table Name=x32
x74=.RevertX7
;x32=x32
;GL=GL
[VPinballX]
;Default value used when not found in the table below.
Default=VPinballX8_1769.exe
Default.RevertX7=VPinballX74.exe
;File versions converted to the right VPinballXxx.exe
;10.60=VPinballX74.exe
;10.70=VPinballX74.exe
;10.72=VPinballX74.exe

the log :

> 2023-12-01 09:29:55 Using default version 10.80 mapped to "C:\vPinball\VisualPinball\VPinballX8_1769.exe"
2023-12-01 09:30:51 Found table version 10.60 of "C:\vPinball\VisualPinball\Tables\Star Fire (Playmatic 1985) 1.1 Eng.vpx" mapped to "C:\vPinball\VisualPinball\VPinballX8_1769.exe"
2023-12-01 09:31:51 Found x74 in C:\vPinball\VisualPinball\Tables\Star Trek LE (Stern 2013)_Bigus(MOD)2.1_x74.vpx
2023-12-01 09:31:51 Found table version 10.72 of "C:\vPinball\VisualPinball\Tables\Star Trek LE (Stern 2013)_Bigus(MOD)2.1_x74.vpx" mapped to "C:\vPinball\VisualPinball\VPinballX8_1769.exe"


At first i started your starter.exe alone. It started the default - my ...X8_1769.exe
OK

Then i started an "old" table. Your starter.exe found a table version 10.60 in it, but because i have no definition for 10.60 in the ini, it started the default X8_1769.exe
OK

Then i started one of the "problematic" tables, where i added "_x74" into the tablename.
Your starter.exe identified this addition - clear, because i set it in TableNameExceptions in the ini
And your starter.exe found the table version 10.72 in it
But then your starter.exe don't look further in the ini, where i told to start the ...X74.exe, if this addition is found
Instead your starter.exe mapped and started the default X8.exe (ok, because there is no definition for 10.72 in the ini)

But i don't want a default definition for 10.72 in the ini, because then ALL 10.72 tables would start with the defined X7.exe

Maybe you can tell your starter.exe to not look further for the table version, if a NameException is found.

**Comment by JockeJarre** [comment]
I have commited a test which should show up in the actions tab, if you want to test.

What it does now, if it doesn't find the VPX version for your table, it applies "Default" as the version.
When it goes through the TableNameExceptions list, and finds the defintion for Default.RevertX7 among the VPinballX executables it will use this one. 

I hope this is what you meant?

**Comment by JockeJarre** [comment]
Will now put it as 1.3 prerelease. 
Thanks for the suggestion!

**Comment by Karl030167** [comment]
Hi,
thank you, now this works as designed ;-)
One hint: the NameExceptions are CASE sensitive.

I set your suggestion ini - with "X74" as exception. But had "...x74..." in the table file name. At start it was mapped to default (X8.exe)
With "...X74..." in table file name then your starter.exe mapped to the right X74.exe

Again many thanks for your work !

Karl (digital.arts)

**Comment by JockeJarre** [comment]
Will add the hint to the documentation
